## THEME
theme: hugolify-theme

## LANGUAGE
defaultContentLanguage: en
languageCode: en

## ADVANCED
paginate: 60
enableRobotsTXT: true
markup:
  tableOfContents:
    ordered: true
build:
  writeStats: true

## STATIC
staticDir:
  - static1
  - static2
