## LANGUAGE
defaultContentLanguage: fr
languageCode: fr

## ADVANCED
build:
  writeStats: true
enableRobotsTXT: true
imaging:
  quality: 75
markup:
  tableOfContents:
    ordered: true
pagination:
  pagerSize: 100
removePathAccents: true
