_merge: deep

# Image
image:
  _merge: deep
  desktop: "678x"

# Javascripts
animation: false
bootstrap:
  alert: false 
  carousel: false 
  collapse: false 
  dropdown: false 
  modal: false 
  offcanvas: true 
  popover: false
  scrollspy: false
  tab: false
  toast: false
  tooltip: false
carousel: false
map: false
parallax:
  enable: false

# Admin
admin:

  # CMS
  cms: decapcms
  branch: main
  git: github
  repo: sebousan/sebastienmoulene
  i18n: 
    locales: '[fr,en]'
  auth:
    netlify_identity: false

  # Collections
  collections:
    config:
      enable: true
    indexes:
      enable: false
    pages:
      enable: false