_merge: deep

# Image
image:
  _merge: deep
  desktop: "678x"

# Javascripts
animation: false
bootstrap:
  alert: false 
  carousel: false 
  collapse: false 
  dropdown: false 
  modal: false 
  offcanvas: true 
  popover: false
  scrollspy: false
  tab: false
  toast: false
  tooltip: false
carousel: false
map: false
parallax:
  enable: false

# Admin
admin:
  cms: decapcms
  git: github
  repo: sebousan/sebastienmoulene
  auth:
    netlify_identity: false
  collections:
    config:
      enable: true
    indexes:
      enable: false
    pages:
      enable: false