_merge: deep
image:
  _merge: deep
  desktop: "678x"
bootstrap:
  alert: false 
  carousel: false 
  collapse: false 
  dropdown: false 
  modal: false 
  offcanvas: true 
  popover: false
  scrollspy: false
  tab: false
  toast: false
  tooltip: false
admin:
  cms: pagescms
  collections:
    config:
      enable: true
    indexes:
      enable: false
    pages:
      enable: false