_merge: deep

# Image
image:
  _merge: deep
  desktop: "806x"
  retina:
    desktop: true

# Javascripts
animation: false
bootstrap:
  alert: false 
  carousel: false 
  collapse: false 
  dropdown: false 
  modal: false 
  offcanvas: true 
  popover: false
  scrollspy: false
  tab: false
  toast: false
  tooltip: false
carousel: false
map: false
parallax:
  enable: false

# Admin
admin:
  cms: sveltiacms
  git: github
  repo: sebousan/sebastienmoulene
  i18n:
    default_locale: fr # master lang for an i18n website
    locales: "[fr,en]" 
  auth:
    netlify_identity: false
  collections:
    config:
      enable: true
    indexes:
      enable: false
    pages:
      enable: false