media:
  input: assets/images/uploads
  output: /images/uploads


content:
- create: true
  description: Tous les projets
  editor:
    preview: false
  fields:
  - default: false
    hidden: true
    i18n: false
    label: is not index
    name: isIndex
    required: false
    type: boolean
  - default: true
    i18n: true
    label: Brouillon
    name: draft
    required: false
    type: boolean
  - default: '{{now}}'
    i18n: duplicate
    label: Date
    name: date
    required: true
    type: date
  - hint: Displayed in tabs, search results, and in SMS/Messages/Social networks preview
    i18n: true
    label: Titre de la page
    name: title
    required: true
    type: string
  - hint: Displayed in tabs, search results, and in SMS/Messages/Social networks preview
    i18n: true
    label: Description
    name: description
    required: false
    type: text
  - hint: ""
    i18n: duplicate
    label: Types
    label_singular: Type
    name: projects_types
    options:
      collection: projects_types
      multiple: true
      search: title
    required: false
    type: reference
  - hint: ""
    i18n: duplicate
    label: Tags
    label_singular: Tag
    name: projects_tags
    options:
      collection: projects_tags
      image: '{image.src}'
      multiple: true
    required: false
    type: reference
  - collapsed: true
    fields:
    - choose_url: false
      hint: 'Redimensionner et compresser l’image avant l’envoi : https://bulkresizephotos.com/fr?quality=90&type=width&width=1600'
      i18n: duplicate
      label: Image
      media_library:
        config:
          max_file_size: 700000
      media_type: collection
      name: src
      path: /images/uploads
      public_type: collection
      required: false
      type: image
    - hint: Pour une image qui transmet des informations (laisser vide si image décorative)
      i18n: true
      label: Texte alternatif
      name: alt
      required: false
      type: string
    hint: Displayed in search results, and in SMS/Messages/Social networks preview
    i18n: true
    label: Image principale
    name: image
    required: false
    type: object
  - collapsed: true
    fields:
    - i18n: true
      label: Sur-titre
      name: surtitle
      required: false
      type: string
    - i18n: true
      label: Titre
      name: title
      required: false
      type: string
    - buttons:
      - bold
      - italic
      - link
      - bulleted-list
      editor_components: []
      i18n: true
      label: Texte
      minimal: true
      modes:
      - rich_text
      name: text
      required: false
      type: rich-text
    - allow_add: true
      collapsed: true
      fields:
      - i18n: true
        label: Texte
        name: text
        required: false
        type: string
      - i18n: true
        label: URL
        name: url
        required: false
        type: string
      - hint: Enter code lang (e.g. fr) if different of the current page language
        i18n: true
        label: Langue
        name: lang
        required: false
        type: string
      - i18n: true
        label: Nouvelle fenêtre ?
        name: blank
        required: false
        type: boolean
      i18n: true
      label: CTAs
      label_singular: CTA
      list: true
      max: 2
      min: 0
      name: ctas
      required: false
      summary: '{{fields.text}}'
      type: object
    - collapsed: true
      fields:
      - choose_url: false
        hint: 'Redimensionner et compresser l’image avant l’envoi : https://bulkresizephotos.com/fr?quality=90&type=width&width=1600'
        i18n: duplicate
        label: Image
        media_library:
          config:
            max_file_size: 700000
        media_type: collection
        name: src
        path: /images/uploads
        public_type: collection
        required: false
        type: image
      - hint: Pour une image qui transmet des informations (laisser vide si image
          décorative)
        i18n: true
        label: Texte alternatif
        name: alt
        required: false
        type: string
      - buttons:
        - link
        editor_components: []
        i18n: true
        label: Crédit
        minimal: true
        modes:
        - rich_text
        name: credit
        required: false
        type: rich-text
      i18n: true
      label: Image
      name: image
      required: false
      type: object
    - hint: ""
      i18n: duplicate
      label: Alignement
      name: align
      options:
        values:
        - label: Start
          value: start
        - label: Center
          value: center
        - label: End
          value: end
      type: select
    i18n: true
    label: Hero
    name: hero
    required: false
    type: object
  - fields:
    - i18n: true
      label: Titre
      name: title
      required: false
      type: string
    - i18n: true
      label: Texte
      name: text
      required: false
      type: string
    i18n: true
    label: Données
    label_singular: Donnée
    list: true
    name: datas
    required: false
    summary: '{{fields.title}}'
    type: object
  - collapsed: true
    fields:
    - choose_url: false
      hint: 'Redimensionner et compresser l’image avant l’envoi : https://bulkresizephotos.com/fr?quality=90&type=width&width=1600'
      i18n: duplicate
      label: Image
      media_library:
        config:
          max_file_size: 700000
      media_type: collection
      name: src
      path: /images/uploads
      public_type: collection
      required: false
      type: image
    - hint: Pour une image qui transmet des informations (laisser vide si image décorative)
      i18n: true
      label: Texte alternatif
      name: alt
      required: false
      type: string
    - buttons:
      - link
      editor_components: []
      i18n: true
      label: Crédit
      minimal: true
      modes:
      - rich_text
      name: credit
      required: false
      type: rich-text
    - i18n: true
      label: Légende
      name: legend
      required: false
      type: string
    - i18n: duplicate
      label: Moitié ?
      name: half
      required: false
      type: boolean
    i18n: true
    label: Images
    list: true
    name: images
    required: false
    type: object
  - hint: Leave empty to automate with the title. **Be carefull to SEO impact.**
    i18n: true
    label: Slug
    name: slug
    pattern:
      message: Contain only lowercase letters, numbers, and hyphens, with no spaces,
        accents, or special characters
      regex: ^(|[a-z0-9-]&#43;)$
    required: false
    type: string
  filename: '{year}/{fields.title}.md'
  i18n: true
  label: Projets
  label_singular: Projet
  name: projects
  path: content/projects
  type: collection
- create: true
  description: Tous les tags projets
  editor:
    preview: false
  fields:
  - default: false
    hidden: true
    i18n: false
    label: is not index
    name: isIndex
    required: false
    type: boolean
  - default: true
    i18n: true
    label: Brouillon
    name: draft
    required: false
    type: boolean
  - hint: Displayed in tabs, search results, and in SMS/Messages/Social networks preview
    i18n: true
    label: Titre de la page
    name: title
    required: true
    type: string
  - hint: Displayed in tabs, search results, and in SMS/Messages/Social networks preview
    i18n: true
    label: Description
    name: description
    required: false
    type: text
  - hint: Leave empty to automate with the title. **Be carefull to SEO impact.**
    i18n: true
    label: Slug
    name: slug
    pattern:
      message: Contain only lowercase letters, numbers, and hyphens, with no spaces,
        accents, or special characters
      regex: ^(|[a-z0-9-]&#43;)$
    required: false
    type: string
  filename: '{fields.title}/_index.md'
  i18n: true
  label: Tags
  label_singular: Tag
  name: projects_tags
  nested:
    depth: 2
  path: content/projects_tags
  type: collection
- create: true
  description: Tous les types de projets
  editor:
    preview: false
  fields:
  - default: false
    hidden: true
    i18n: false
    label: is not index
    name: isIndex
    required: false
    type: boolean
  - default: true
    i18n: true
    label: Brouillon
    name: draft
    required: false
    type: boolean
  - hint: Displayed in tabs, search results, and in SMS/Messages/Social networks preview
    i18n: true
    label: Titre de la page
    name: title
    required: true
    type: string
  - hint: Displayed in tabs, search results, and in SMS/Messages/Social networks preview
    i18n: true
    label: Description
    name: description
    required: false
    type: text
  - hint: Leave empty to automate with the title. **Be carefull to SEO impact.**
    i18n: true
    label: Slug
    name: slug
    pattern:
      message: Contain only lowercase letters, numbers, and hyphens, with no spaces,
        accents, or special characters
      regex: ^(|[a-z0-9-]&#43;)$
    required: false
    type: string
  filename: '{fields.title}/_index.md'
  i18n: true
  label: Types
  label_singular: Type
  name: projects_types
  nested:
    depth: 2
  path: content/projects_types
  type: collection

