

content:
- create: true
  description: All news
  editor:
    preview: false
  fields:
  - default: false
    hidden: true
    i18n: false
    label: is not index
    name: isIndex
    required: false
    widget: string
  - default: true
    i18n: true
    label: Draft
    name: draft
    required: false
    widget: boolean
  - default: '{{now}}'
    i18n: duplicate
    label: Date
    name: date
    required: true
    widget: date
  - hint: Displayed in tabs, search results, and in SMS/Messages/Social networks preview
    i18n: true
    label: Page title
    name: title
    required: true
    widget: string
  - hint: Displayed in tabs, search results, and in SMS/Messages/Social networks preview
    i18n: true
    label: Description
    name: description
    required: false
    widget: text
  - collapsed: true
    fields:
    - choose_url: false
      hint: 'Resize and compress image before sending : https://bulkresizephotos.com/fr?quality=90&amp;type=width&amp;width=1600'
      i18n: duplicate
      label: Image
      media_library:
        config:
          max_file_size: 700000
      media_type: collection
      name: src
      path: /images/uploads
      public_type: collection
      required: false
      widget: image
    - hint: For an image that conveys information (leave blank if decorative image)
      i18n: true
      label: Text alternative
      name: alt
      required: false
      widget: string
    hint: Displayed in search results, and in SMS/Messages/Social networks preview
    i18n: true
    label: Image principale
    name: image
    required: false
    widget: object
  - i18n: true
    label: Body
    name: body
    required: false
    widget: rich-text
  - hint: Leave empty to automate with the title. **Be careful to SEO impact.**
    i18n: true
    label: Slug
    name: slug
    pattern:
    - ^(|[a-z0-9-]+)$
    - Contain only lowercase letters, numbers, and hyphens, with no spaces, accents,
      or special characters
    required: false
    widget: string
  filename: '{year}/{month}/{fields.title}.md'
  i18n: true
  label: News
  label_singular: New
  name: posts
  path: content/posts
  type: collection
media:
  input: static/images/uploads
  output: /images/uploads

