content:
- type: collection
  description: All news
  filename: '{year}/{month}/{slug}.md'
  path: content/posts
  label: News
  name: posts
  fields:
  - hint: Displayed in tabs, search results, and in SMS/Messages/Social networks preview
    i18n: true
    label: Page title
    name: title
    required: true
    type: string
  - i18n: true
    label: Body
    name: body
    required: false
    type: rich-text
media:
  input: static/images/uploads
  output: /images/uploads
