
collections_config:
  pages:
    path: content
    icon: file
    
    _inputs:
      title:
        type: text
        comment: Titre de la page
      date:
        type: datetime
        comment: Date de publication
      draft:
        type: boolean
        comment: Brouillon
      description:
        type: markdown
        comment: Description de la page
      blocks:
        type: array
        options:
          structures: _structures.content_blocks

  projects:
    path: content/projects
    icon: file
    
    _inputs:
      title:
        type: text
        comment: Titre du projet
  
  projects_tags:
    path: content/projects_tags
    icon: file
    
    _inputs:
      title:
        type: text
        comment: Titre du tag

collection_groups:
  - heading: Pages
    collections:
      - pages
  - heading: Projects
    collections:
      - projects
      - projects_tags

_structures:
  blocks:
    values:
      - label: "Bloc Image"
        icon: "image"
        value:
          type: "image_block"
          image: ""
          text: ""
      - label: "Bloc Citation" 
        icon: "format_quote"
        value:
          type: "quote_block"
          quote: ""
          author: ""